name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  ACRNAME: enkelconnectacr
  IMAGE_NAME: enkelconnectfe
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: <your-azure-container-registry-name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Get Docker Image from ACR
        run: |
          docker pull ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
     
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'