# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# src: .github/workflows/
name: Build and deploy a container to an Azure Container Apps - ACA

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: enkelconnectfe
  CONTAINERAPPS_APP: acaenkelconnectdev01
  CONTAINERAPPS_ENVIRONMENT: acaenv-enkelconnect-dev-01
  RESOURCE_GROUP: EnkelConnect-RG-Dev
  VERSION: $(( $(cat version.txt) + 1 ))
  ACRNAME: acrenkelconnectdev01

permissions:
  contents: read
  packages: write

jobs:
  build-push-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container image to registry
        run: |
          docker build -t ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
 #         docker push ${{ env.ACRNAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

